### ISSUE TITLE
Package `rlang` test suite runs orders of magnitude slower with `covr.record_tests`

### ISSUE THREAD

**Issue by dgkf** [Genentech/covtracer#42]
Although this would probably require changes to `covr`, I'm logging this here to investigate and identify what changes would be needed to `covr`'s `options(covr.record_tests = TRUE)` behavior to accommodate it. 

In one experiment, `rlang`'s test suite ran in ~1min regularly, but would take ~6hr when recording tests. 

Knowing that `covr`, the `record_tests` behavior and `rlang` are all doing some pretty wild stuff with the call stack and modifying execution patterns, this could be a hairy issue - perhaps attempting to update the test traces far too frequently (meaning the heuristics for determining when we have not hit a new test are still performing poorly) or hitting some memory limit that starts to use swap during execution and bog things down considerably.

**Comment by maksymiuks** [comment]
After merging the fix for this issue into the covr's master we are experiencing issues in the covtracer. In detail, it crashes for packages that do not use testthat. Here is the investigation I've done so far:

The package crashes only for non test that packages and this is the exact line causing problems

https://github.com/Genentech/covtracer/blob/main/R/test_trace_df.R#L102

test_mat is a matrix with row count higher than 0 and "test" column unanimously equal 0. Therefore `tests_df[test_mat[, "test"], ]` is returning an empty data.frane (0 rows) and cbind cannot merge them.

Previously, before covr package was updated, test_mat was empty data.frame  thus cbind was working without any problems.

In summarizing, for some reason this line https://github.com/Genentech/covtracer/blob/main/R/test_trace_df.R#L73 now returns a non-empty data frame that doesn't number tests (`"test"` column unanimously equal 0) while previously it was an empty data.frame.

@dgkf Do you have any idea where the difference come from?

**Comment by dgkf** [comment]
Thanks - I'll investigate. I did a bit squash and rebase at the end of this PR and I think I may have improperly squashed some changes. At one point, the matrix was initialized with `NA`s, and filtered out any `NA`s. 

I'll investigate later today, but I suspect maybe the 0-default and NA-default behaviors might have gotten intertwined.

**Comment by dgkf** [comment]
Closing this out. This resulted in changes to `covr` that optimized some of the allocation of trace call stacks.
